language: en-US

early_access: false

# Review settings
reviews:
  # Review every pull request
  auto_review:
    enabled: true
    # Trigger on these events
    drafts: true
    base_branches:
      - "*"

  # Review configuration
  profile: assertive

  # Request changes for critical issues
  request_changes_workflow: true

  # High-level summary
  high_level_summary: true

  # Review status comment
  review_status: true

  # Collapse walkthrough details
  collapse_walkthrough: false

  # Sequence diagrams for flow changes
  sequence_diagrams: true

  # Path-based instructions for specific file types
  path_instructions:
    - path: "src/**/*.{ts,tsx,js}"
      instructions: |
        Review the React.js/TypeScript/JavaScript code for best practices and potential bugs.
        Ensure that the code adheres to TypeScript's typing system and modern standards.
        Ensure sufficient error handling and logging is present.
        Check for common security vulnerabilities such as:
          - SQL Injection
          - XSS (Cross-Site Scripting)
          - CSRF (Cross-Site Request Forgery)
          - Insecure dependencies
          - Sensitive data exposure

    - path: "**/*.css"
      instructions: |
        - Check for unused styles
        - Look for responsive design issues
        - Verify CSS naming conventions

    - path: "**/*.md"
      instructions: |
        - Check for broken links
        - Verify markdown formatting
        - Check for spelling and grammar

  # Files and paths to include or exclude
  path_filters:
    - "node_modules/**"
    - "dist/**"
    - "build/**"
    - "coverage/**"
    - "*.min.js"
    - "*.min.css"
    - "package-lock.json"
    - "yarn.lock"
    - "pnpm-lock.yaml"
    - "bun.lockb"
    - ".git/**"
    - ".github/**"
    - "public/assets/**"

  # Tools configuration
  tools:
    # Shellcheck for shell scripts
    shellcheck:
      enabled: true

# Tone and style of reviews
tone_instructions: |
  - Be constructive and encouraging
  - Explain the reasoning behind suggestions
  - Provide examples when suggesting changes
  - Focus on security, performance, and maintainability
  - Be respectful and professional

# Chat settings
chat:
  auto_reply: true
