name: Setup Bun workspace
runs:
  using: composite
  steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: 1.3.9
    - uses: actions/cache@v4
      with:
        path: ~/.bun/install/cache
        key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lock') }}
        restore-keys: ${{ runner.os }}-bun-
    - run: bun install --frozen-lockfile
      shell: bash